default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: briefly_development

test:
  <<: *default
  database: briefly_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

